name: "Cached Docker Build"
description: "Use Github Action's cache to store and retrieve docker images"

branding:
  icon: "layers"
  color: "red"

inputs:
  args:
    description: "docker build args"
    required: true
  cache_key:
    description: "Cache key"
    required: true
  expires:
    description: "Set expiration for cache (example '12 hours' or '3 days', ...)"

# ${{runner.temp}} directory is guaranteed to be empty at the start of each job, even on self-hosted runners.

runs:
  using: "node12"
  main: "dist/index.js"

